# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database:
            entity:
                class: AppBundle:User
                property: username
        in_memory:
            memory:
                users:
                    vincent:
                          password: $2y$13$CPNqTpJs3OkeTM6gZz5dTeZvbkmWXV8Z8lKyyz4qoVBD/8Lqgrh8.
                          roles: 'ROLE_USER'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/(login|register)$
            anonymous: ~
#            security: false

        secured_area:
            pattern: ^/
            provider: database
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /courses
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
